server:
  port: 10001
logging:
  config: classpath:log4j-dev.xml
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shutter?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    hikari:
      auto-commit: true #此属性控制从池返回的连接的默认自动提交行为，默认值：true
      pool-name: ShutterConsoleDBPool
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟)
      max-lifetime: 1800000 #控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000，即30分钟
      connection-timeout: 10000 #数据库连接超时时间,默认30秒，即30000
knife4j:
  enable: true
sa-token:
  is-log: true