spring:
  application:
    name: Shutter Console
  servlet:
    multipart:
      # 请求数据大小
      max-request-size: 100MB
      # 上传文件大小
      max-file-size: 100MB
  # 时间正反序列化格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 兼容Knife4j
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: X-SHUTTER-ACCESS-TOKEN
  # token有效期，单位s 默认1天, -1代表永不过期
  timeout: 86400
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录(为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时(为true共用一个token, 为false每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 开启日志
  is-log: true
knife4j:
  enable: true
shutter:
  # Knife4j配置
  knife4j:
    enabled: true
    title: Shutter Console API
    version: 1.0.0
    description: Shutter Console API
    author: xuepeng
    website: https://gitee.com/xzr0710/shutter
    email: 100103081@qq.com
  # 业务模块配置
  module:
    system:
      sys-user-property:
        # 随机密码的长度
        random-password-length: 8
        # 密码加密策略
        password-strategy-type: bcrypt
  # 权限配置
  auth:
    include-path: /**
    exclude-paths:
      - /v1/auth/v1/verify-code
      - /v1/auth/v1/login